config/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('admin_tools/', include('admin_tools.urls')),
    path('', include('myapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(), name='logout'),
    path('accounts/password_change/', views.PasswordChangeView.as_view(),
         name='password_change'),
    path('accounts/password_change/done/',
         views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('accounts/password_reset/', views.PasswordResetView.as_view(),
         name='password_reset'),
    path('accounts/password_reset/done/', views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',
         views.PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/', views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
]

myapp/urls.py
from django.urls import path

from . import views

app_name = 'myapp'
urlpatterns = [
    path('creating/', views.CreatingView.as_view(), name='creating'),
]

templates/base.html
<!doctype html>
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='slim' %}
<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %}</title>

    {# --- css --- #}
    <link rel="stylesheet"
          href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css"
          integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX"
          crossorigin="anonymous">
    <style type="text/css">
        .datepicker-days th.dow:first-child,
        .datepicker-days td:first-child {
            color: #f00;
        }

        .datepicker-days th.dow:last-child,
        .datepicker-days td:last-child {
            color: #00f;
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand">CreatingSlackChannels</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:creating' %}">CreateChannels</a>
                </li>
            </ul>
        </div>
    </nav>
</header>


<body>
<main class="container">
    {% block content %}
    {% endblock %}
</main>

{# --- js --- #}
<!--
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
-->
{% block extra_js %}{% endblock %}
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
</body>
</html>

templates/creating.html
{% extends "base.html" %}
{% load static %}

{% block title %}チャンネル作成{% endblock %}

{% block content %}

{% if user.is_superuser %}

{% csrf_token %}
<div class="card" style="width: 50rem;">
    <div class="card-header"><h2>
        チャンネル作成
    </h2></div>
    <div class="card-body">
        <p class="card-text">ようこそ {{ user.get_username }} さん</p>
        <form method="post">
            {% csrf_token %}
            <label for="name">メンター部屋-<input type="text" id="name" name="name">様</label>
            <br>
            <label for="plan">契約プラン：</label>
            <input type="text" id="plan" name="plan">
            <br>
            <label for="date1">契約期間：<input type="number" id="date1" name="date1"
                                           size="3"></label>
            <label for="date2">日~翌月<input type="number" id="date2" name="date2"
                                          size="3"></label>
            <label for="date3">（<input type="number" id="date3" name="date3"
                                       size="3">日に自動更新）</label>
            <br>
            <label for="mentee_id">メンティーID(ブランク可)</label><input type="text"
                                                                id="mentee_id"
                                                                name="mentee_id">
            <br>
            <button class="btn btn-primary" type="submit" name="send" id="send">
                送信する
            </button>
        </form>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
        <script>
            $(function () {
                $('#send').on('click', function () {
                    if ($('#name').val() === '' ||
                        $('#plan').val() === '' ||
                        $('#date1').val() === '' ||
                        $('#date2').val() === '' ||
                        $('#date3').val() === '') {
                        alert('空白があります');
                        return false;
                    }
                });
            });
        </script>
        <style>
            input[type="number"] {
                width: 50px;
            }
        </style>
    </div>
</div>
<br>
<p><a href="{% url 'logout' %}">ログアウト</a></p>
{% else %}
<div class="card" style="width: 50rem;">
    <div class="card-header"><h2>
        ログイン画面へ
    </h2></div>
    <div class="card-body">
        <p><a href="{% url 'login' %}">ログイン</a></p>
    </div>
</div>
{% endif %}
{% endblock %}

templates/creating_done.html
{% extends "base.html" %}

{% block title %}作成完了{% endblock %}

{% block content %}
<h2>チャンネル作成完了</h2>
<h3>メンター部屋-{{ name }}様</h3>
<a href="{% url 'myapp:creating' %}">ホームに戻る</a>
{% endblock %}

templates/creating_failed.html
{% extends "base.html" %}

{% block title %}作成失敗{% endblock %}

{% block content %}
<h2>チャンネル作成失敗</h2>
<h3>エラー：コード{{ error_id }}_{{ title }}でエラーが発生しました</h3>
<h3>エラー情報：</h3>
<p>'ok': {{ ok }}</p>
<p>'error': {{ error }}</p>
<p>'errors': {{ errors }}</p>
<p>'detail': {{ detail }}</p>
<h3>注意：</h3>
{% if error_id == 1 %}
<h3>チャンネル作成で失敗しました。<br>
    すでに同一の名前が存在する可能性が高いです。
</h3>
{% endif %}
{% if error_id == 2 %}
<h3>定型文の送信で失敗しました。</h3>
{% elif error_id == 3 %}
<h3>トピックの設定で失敗しました。</h3>
{% elif error_id == 4 %}
<h3>
    メンターの招待で失敗しました。<br>
    初期設定で入力したIDが間違っている可能性があります。
</h3>
{% elif error_id == 5 %}
<h3>
    メンティーの招待で失敗しました。<br>
    フォームで入力したIDが間違っている可能性があります。
</h3>
<h3>
    <br>
    入力した名前でチャンネルが不完全に作られた可能性が高いです。<br>
    やり直す場合はslackでチャンネルを削除してください。
</h3>
{% endif %}
{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}ホーム{% endblock %}

{% block content %}
<h2>ホーム</h2>
{% if user.is_authenticated %}
ようこそ {{ user.get_username }} さん
<p><a href="{% url 'logout' %}">ログアウト</a></p>
{% else %}
<p><a href="{% url 'login' %}">ログイン</a></p>
{% endif %}
{% endblock %}